name: testing-build

on:
  push:

env:
  DEPLOYMENT: some-deployment

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print out the environment
        run: |
          echo "Hello, world!"
          echo "The current time is $(date)."
          echo "The current directory is $(pwd)."
          echo "The current directory contents are:"
          ls -l
          export BRANCH=$(echo ${GITHUB_REF_NAME}|sed 's|/|-|g')
          export SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          export IMAGE_TAG="${DEPLOYMENT}:${BRANCH}-${SHORT_SHA}"
          tee foo.json <<EOF
          {
            "fullSha": "${GITHUB_SHA}",
            "shortSha": "${SHORT_SHA}",
            "tag": "${IMAGE_TAG}",
            "deployment": "${DEPLOYMENT}"
          }
          EOF
      # Save artifacts
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: foo
          path: foo.json