name: testing-build

on:
  push:

env:
  DEPLOYMENT: some-deployment

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print out the environment
        run: |
          echo "Hello, world!"
          echo "The current time is $(date)."
          echo "The current directory is $(pwd)."
          echo "The current directory contents are:"
          ls -l
          export BRANCH=$(echo ${GITHUB_REF_NAME}|sed 's|/|-|g')
          export SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          export IMAGE_TAG="someorg/${DEPLOYMENT}:${BRANCH}-${SHORT_SHA}"
          tee deployment.json <<EOF
          {
            "fullSha": "${GITHUB_SHA}",
            "shortSha": "${SHORT_SHA}",
            "tag": "${IMAGE_TAG}",
            "deployment": "${DEPLOYMENT}"
          }
          EOF
      # Save artifacts
      - name: Save artifacts
        if: github.ref_name == 'staging' || github.ref_name == 'main'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref_name }}-deployment
          path: deployment.json

  test-reusable-workflow:
    needs: sanity-check
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      workflow: test-build

