name: get-artifacts-from-another-workflow
on:
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Workflow name'
        required: true
        default: 'test-build.yml'

jobs:
  get-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.inputs.workflow }}
          workflow_conclusion: success

      - name: Print out the environment
        run: |
          echo "Hello, world!"
          echo "The current time is $(date)."
          echo "The current directory is $(pwd)."
          echo "The current directory contents are:"
          ls -l

          cat foo/foo.json|jq

          export SHORT_SHA=$(cat foo/foo.json|jq -r .shortSha)
          export FULL_SHA=$(cat foo/foo.json|jq -r .fullSha)
          export IMAGE_TAG=$(cat foo/foo.json|jq -r .tag)
          export DEPLOYMENT=$(cat foo/foo.json|jq -r .deployment)
          echo "SHORT_SHA: ${SHORT_SHA}"
          echo "FULL_SHA: ${FULL_SHA}"
          echo "IMAGE_TAG: ${IMAGE_TAG}"
          echo "DEPLOYMENT: ${DEPLOYMENT}"
