name: dispatch-deploy
on:
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Workflow name'
        required: true
        default: 'test-build'
        type: string

jobs:
  deploy:
    uses: .github/workflows/reusable-deploy.yml
    with:
      workflow: ${{ inputs.workflow }}
      from-trigger: true
