name: get-artifacts-from-another-workflow
on:
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Workflow name'
        required: true
        default: 'test-build.yml'

jobs:
  get-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.inputs.workflow }}
          workflow_conclusion: success

      - name: Print out the environment
        run: |
          echo "Hello, world!"
          echo "The current time is $(date)."
          echo "The current directory is $(pwd)."
          echo "The current directory contents are:"
          ls -l

          cat foo/foo.json|jq